# Generated by Django 3.2.13 on 2022-04-14 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rplace', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tile',
        ),
    ]
