# Generated by Django 3.2.13 on 2022-04-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rplace', '0002_delete_tile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RplaceTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=88, null=True)),
                ('pixel_color', models.CharField(blank=True, max_length=7, null=True)),
                ('coordinate', models.CharField(blank=True, max_length=21, null=True)),
            ],
            options={
                'db_table': 'rplace_tile',
                'managed': False,
            },
        ),
    ]
